# Generated by Django 4.1.5 on 2023-01-12 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_todo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Todo',
        ),
    ]
